#!/usr/bin/env python3
"""
Hook: session_report
Trigger: Stop (agent finishes or is interrupted)
Purpose: Write a concise session summary to .session_log.md so the next
session (or human reviewer) can instantly see what was done and what remains.

Appends to .session_log.md — does not overwrite previous sessions.
"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def read_safe(path: str) -> str:
    try:
        return Path(path).read_text(encoding="utf-8")
    except Exception:
        return ""


def files_modified_this_session() -> list[str]:
    """
    Approximate: list files modified in the last hour.
    In a real Claude Code environment the hook receives tool call history —
    here we use mtime as a proxy.
    """
    recent = []
    cutoff = datetime.now(timezone.utc).timestamp() - 3600  # last 60 min
    for dirpath, dirnames, filenames in os.walk("."):
        # Skip hidden and noise directories
        dirnames[:] = [
            d for d in dirnames
            if not d.startswith(".") and d not in ("node_modules", "__pycache__", ".git")
        ]
        for fname in filenames:
            fpath = os.path.join(dirpath, fname)
            try:
                if os.path.getmtime(fpath) > cutoff:
                    recent.append(fpath.lstrip("./"))
            except OSError:
                continue
    return sorted(recent)


def count_todos() -> int:
    count = 0
    for dirpath, dirnames, filenames in os.walk("."):
        dirnames[:] = [d for d in dirnames if not d.startswith(".") and d not in ("node_modules",)]
        for fname in filenames:
            if not fname.endswith((".py", ".ts", ".tsx", ".js", ".jsx")):
                continue
            content = read_safe(os.path.join(dirpath, fname))
            count += content.count("# TODO:") + content.count("// TODO:")
    return count


def open_questions_from_prd() -> list[str]:
    content = read_safe("PRD.md")
    match = re.search(r"##\s+Open Questions(.+?)(?=\n##|\Z)", content, re.DOTALL)
    if not match:
        return []
    return re.findall(r"- \[ \] (.+)", match.group(1))


def load_snapshot() -> dict:
    try:
        return json.loads(Path(".context_snapshot.json").read_text())
    except Exception:
        return {}


def build_report() -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    modified = files_modified_this_session()
    todos = count_todos()
    open_qs = open_questions_from_prd()
    snapshot = load_snapshot()
    stage = snapshot.get("pipeline", {}).get("inferred_stage", "unknown")
    resume_hint = snapshot.get("resume_hint", "—")
    stubs = snapshot.get("code", {}).get("stubs", [])

    lines = [
        f"\n---\n",
        f"## Session — {now}",
        f"",
        f"**Pipeline stage:** `{stage}`",
        f"",
    ]

    if modified:
        lines.append("**Files touched this session:**")
        for f in modified[:15]:
            lines.append(f"  - `{f}`")
        if len(modified) > 15:
            lines.append(f"  - ... and {len(modified) - 15} more")
        lines.append("")
    else:
        lines.append("**Files touched:** none detected\n")

    if open_qs:
        lines.append(f"**Open questions in PRD ({len(open_qs)}):**")
        for q in open_qs[:5]:
            lines.append(f"  - [ ] {q}")
        lines.append("")

    if stubs:
        lines.append(f"**Stubs remaining ({len(stubs)}):**")
        for s in stubs[:5]:
            lines.append(f"  - `{s}`")
        lines.append("")

    lines.append(f"**TODOs in code:** {todos}")
    lines.append("")
    lines.append(f"**Resume hint:** {resume_hint}")
    lines.append("")

    return "\n".join(lines)


def main():
    report = build_report()

    log_path = Path(".session_log.md")

    # Create header if file is new
    if not log_path.exists():
        log_path.write_text("# Session Log\n\nAutomatically generated by `hooks/stop/session_report.py`\n")

    # Append this session
    with open(log_path, "a") as f:
        f.write(report)

    print(
        f"📋 Session report appended to '.session_log.md'\n"
        f"   Review it at the start of your next session or share with a team member.",
        file=sys.stderr,
    )

    sys.exit(0)


if __name__ == "__main__":
    main()
